appname: "dan"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
plugins:
  Feed:
    title: chunzi.me
    copyright: chunzi
    tagline: chunzi blog
    description: chunzi.me
